### ISSUE TITLE
Plot Borders can be Stolen with Sticky Pistons.

### ISSUE THREAD

**Issue by MonoAdrian23** [KCodeYT/PlotPlugin#8] opened 2022-06-08 13:51 UTC

**Comment by MonoAdrian23** [comment] 2022-06-08 13:52
Change youre border to beacon or another Block

Place a Sticky Piston powered with Redstone

Now you can steal the Border Block and its Not longer portectected.

**Comment by KCodeYT** [comment] 2022-07-26 14:50
I cant reproduce this error. Are you sure you are using the latest version of this plugin?

**Comment by KCodeYT** [comment] 2022-07-29 20:42
I close this issue. If this error still appears, please create a new issue.

**Closed as completed by KCodeYT** 2022-07-29 20:42 UTC
